services:
  postgres:
    image: "postgres:17"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

  auth-cli:
    build: .
    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: authdb

    stdin_open: true
    tty: true

    command: ./auth-cli

volumes:
  postgres_data:
